### ISSUE TITLE
Raspbian bullseye, sdcard crashes (can't read/write) after activating sd1

### ISSUE THREAD

**Issue by ezplanet** [sfera-labs/iono-pi-max-kernel-module#2]
With buster the second sd card was working OK.
I created a fresh install with bullseye. When I activate the second sd card with:

`echo 1 > /sys/devices/virtual/ionopimax/sd/sd1_enabled`

The first sd card (main or A) fails to read after a few seconds and thus the system crashes.

**Comment by giampiero7** [comment]
Hello,
This can be due to many causes, but it is not related to the kernel module.
Please send an email to support@sferalabs.cc with further details and dmesg logs related to the operation.
Thanks
